### ISSUE TITLE
cant start it

### ISSUE THREAD

**Issue by mikeparadinas** [ZerataX/ebooks#1]
how do I set it up and run it? :)

Traceback (most recent call last):
  File "C:\Users\Admin\x\ebooks.py", line 1, in <module>
    import discord, asyncio, logging, time, threading, markovify, psutil, posixpath, platform, re, requests, os, time, shutil, glob, textwrap, json
  File "C:\Users\Admin\x\markovify__init__.py", line 5, in <module>
    from .text import Text, NewlineText
  File "C:\Users\Admin\x\markovify\text.py", line 4, in <module>
    from unidecode import unidecode
ImportError: No module named 'unidecode'

**Comment by zeratax** [comment]
I apologize for the very late response, for some reason I never got a notification.

Anyways if you are still interested, you probably just didn't install the necessary libraries.
If you have pip just do:

```
pip3.5 install markovify python-pillow pyfiglet
```

or check their individual pages for more info:
[discord.py](https://github.com/Rapptz/discord.py), [markovify](https://github.com/jsvine/markovify), [python-pillow](https://github.com/python-pillow/Pillow) and [pyfiglet](https://github.com/pwaller/pyfiglet)

**Comment by zeratax** [comment]
closing due to lack of response.
